# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GlabOverseer < Formula
  desc "A terminal watcher for GitLab pipelines with live job logs."
  homepage "https://github.com/arvindell/glab-overseer"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arvindell/glab-overseer/releases/download/v1.0.0/glab-overseer_v1.0.0_darwin_amd64.tar.gz"
      sha256 "48a93f49921a00ebb58f8934c3d6babbc6a95b5fffaeab69c7f7e8fafcba6df3"

      define_method(:install) do
        bin.install "glab-overseer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arvindell/glab-overseer/releases/download/v1.0.0/glab-overseer_v1.0.0_darwin_arm64.tar.gz"
      sha256 "716ffcbd5a05810cc26595b35052c3616ffc4db43ba1fc670460fda4754d6c86"

      define_method(:install) do
        bin.install "glab-overseer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arvindell/glab-overseer/releases/download/v1.0.0/glab-overseer_v1.0.0_linux_amd64.tar.gz"
      sha256 "a12cddbb5affcea4248d69d3658b70cb4bada9b9a3aa47b0330a5361592272c7"
      define_method(:install) do
        bin.install "glab-overseer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arvindell/glab-overseer/releases/download/v1.0.0/glab-overseer_v1.0.0_linux_arm64.tar.gz"
      sha256 "94490d98a5bbe2a5a2fb0b78857005e628dddda0275289469d9d8581a5642eaa"
      define_method(:install) do
        bin.install "glab-overseer"
      end
    end
  end

  test do
    system "#{bin}/glab-overseer", "--version"
  end
end
