# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GlabOverseer < Formula
  desc "A terminal watcher for GitLab pipelines with live job logs."
  homepage "https://github.com/arvindell/glab-overseer"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arvindell/glab-overseer/releases/download/v0.1.3/glab-overseer_v0.1.3_darwin_amd64.tar.gz"
      sha256 "9400ddbf9d1cca1cf089745fc0f80ff18dcbd8a16748c6b63c3c4474ac954519"

      define_method(:install) do
        bin.install "glab-overseer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arvindell/glab-overseer/releases/download/v0.1.3/glab-overseer_v0.1.3_darwin_arm64.tar.gz"
      sha256 "9d0b03eb915edfafb588bbe2e37d46f47b0f2bed0c76c7e2435296cc28a407a0"

      define_method(:install) do
        bin.install "glab-overseer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arvindell/glab-overseer/releases/download/v0.1.3/glab-overseer_v0.1.3_linux_amd64.tar.gz"
      sha256 "665c9bb0e51171c86f1b0bad8e5ed33c6e996859e927e5eb56716bd5a92e4929"
      define_method(:install) do
        bin.install "glab-overseer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arvindell/glab-overseer/releases/download/v0.1.3/glab-overseer_v0.1.3_linux_arm64.tar.gz"
      sha256 "4697ba25249463d0a77bc38fca9f7ac1639d1fd85dbea11a0eea8d6aefacf2dc"
      define_method(:install) do
        bin.install "glab-overseer"
      end
    end
  end

  test do
    system "#{bin}/glab-overseer", "--version"
  end
end
